add the other stuff in
Signed-off-by: Terry Kong <terryk@nvidia.com>

diff --git a/.github/workflows/cicd-main.yml b/.github/workflows/cicd-main.yml
--- a/.github/workflows/cicd-main.yml
+++ b/.github/workflows/cicd-main.yml
@@ -295,233 +295,233 @@ jobs:
               body: commentBody
             });
 
-  #lint-check:
-  #  name: Lint check
-  #  needs: [pre-flight]
-  #  runs-on: ubuntu-latest
-  #  steps:
-  #    - name: Checkout repository
-  #      uses: actions/checkout@v4
-  #      with:
-  #        submodules: 'recursive'
-  #    - name: Install uv
-  #      uses: astral-sh/setup-uv@v5
-  #      with:
-  #        version: "0.7.2"
-  #        enable-cache: true
-  #        prune-cache: false
-  #    # Faster than uv python install since it caches python alongside runner
-  #    - name: "Set up Python"
-  #      uses: actions/setup-python@v5
-  #      with:
-  #        python-version-file: ".python-version"
-  #    - name: Check lint
-  #      run: |
-  #        uv venv
-  #        uv run --group dev pre-commit install
-  #        uv run --group dev pre-commit run --all-files --show-diff-on-failure --color=always
-  #    - name: Minimize uv cache
-  #      run: uv cache prune --ci
+  lint-check:
+    name: Lint check
+    needs: [pre-flight]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          submodules: 'recursive'
+      - name: Install uv
+        uses: astral-sh/setup-uv@v5
+        with:
+          version: "0.7.2"
+          enable-cache: true
+          prune-cache: false
+      # Faster than uv python install since it caches python alongside runner
+      - name: "Set up Python"
+        uses: actions/setup-python@v5
+        with:
+          python-version-file: ".python-version"
+      - name: Check lint
+        run: |
+          uv venv
+          uv run --group dev pre-commit install
+          uv run --group dev pre-commit run --all-files --show-diff-on-failure --color=always
+      - name: Minimize uv cache
+        run: uv cache prune --ci
 
-  #mypy-check:
-  #  name: Mypy check
-  #  needs: [pre-flight]
-  #  runs-on: ubuntu-latest
-  #  steps:
-  #    - name: Checkout repository
-  #      uses: actions/checkout@v4
-  #    - name: Install uv
-  #      uses: astral-sh/setup-uv@v5
-  #      with:
-  #        version: "0.7.2"
-  #        enable-cache: true
-  #        prune-cache: false
-  #    # Faster than uv python install since it caches python alongside runner
-  #    - name: "Set up Python"
-  #      uses: actions/setup-python@v5
-  #      with:
-  #        python-version-file: ".python-version"
-  #    - name: Check mypy
-  #      run: |
-  #        uv venv
-  #        uv run --group test mypy nemo_rl examples
-  #    - name: Minimize uv cache
-  #      run: uv cache prune --ci
+  mypy-check:
+    name: Mypy check
+    needs: [pre-flight]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+      - name: Install uv
+        uses: astral-sh/setup-uv@v5
+        with:
+          version: "0.7.2"
+          enable-cache: true
+          prune-cache: false
+      # Faster than uv python install since it caches python alongside runner
+      - name: "Set up Python"
+        uses: actions/setup-python@v5
+        with:
+          python-version-file: ".python-version"
+      - name: Check mypy
+        run: |
+          uv venv
+          uv run --group test mypy nemo_rl examples
+      - name: Minimize uv cache
+        run: uv cache prune --ci
 
-  #sphinx-build:
-  #  if: ${{ needs.pre-flight.outputs.test_level != 'none' }}
-  #  name: Sphinx build
-  #  needs: [pre-flight]
-  #  runs-on: ubuntu-latest
-  #  steps:
-  #    - name: Checkout repository
-  #      uses: actions/checkout@v4
-  #      with:
-  #        submodules: 'recursive'
-  #    - name: Install uv
-  #      uses: astral-sh/setup-uv@v5
-  #      with:
-  #        version: "0.7.2"
-  #        enable-cache: true
-  #        prune-cache: false
-  #    # Faster than uv python install since it caches python alongside runner
-  #    - name: "Set up Python"
-  #      uses: actions/setup-python@v5
-  #      with:
-  #        python-version-file: ".python-version"
-  #    - name: build docs
-  #      run: |
-  #        uv venv
-  #        cd docs/
-  #        uv run --group docs sphinx-build --fail-on-warning --builder html . _build/html
-  #    - name: Minimize uv cache
-  #      run: uv cache prune --ci
+  sphinx-build:
+    if: ${{ needs.pre-flight.outputs.test_level != 'none' }}
+    name: Sphinx build
+    needs: [pre-flight]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          submodules: 'recursive'
+      - name: Install uv
+        uses: astral-sh/setup-uv@v5
+        with:
+          version: "0.7.2"
+          enable-cache: true
+          prune-cache: false
+      # Faster than uv python install since it caches python alongside runner
+      - name: "Set up Python"
+        uses: actions/setup-python@v5
+        with:
+          python-version-file: ".python-version"
+      - name: build docs
+        run: |
+          uv venv
+          cd docs/
+          uv run --group docs sphinx-build --fail-on-warning --builder html . _build/html
+      - name: Minimize uv cache
+        run: uv cache prune --ci
 
-  #build-container:
-  #  if: ${{ needs.pre-flight.outputs.test_level != 'none' }}
-  #  needs: [pre-flight]
-  #  uses: NVIDIA-NeMo/FW-CI-templates/.github/workflows/_build_container.yml@v0.30.0
-  #  with:
-  #    build-ref: ${{ github.sha }}
-  #    image-name: nemo_rl_container
-  #    dockerfile: docker/Dockerfile
-  #    image-label: nemo-rl
-  #    target: hermetic
-  #    build-args: |
-  #      MAX_JOBS=32
-  #      NEMO_RL_COMMIT=${{ github.sha }}
+  build-container:
+    if: ${{ needs.pre-flight.outputs.test_level != 'none' }}
+    needs: [pre-flight]
+    uses: NVIDIA-NeMo/FW-CI-templates/.github/workflows/_build_container.yml@v0.30.0
+    with:
+      build-ref: ${{ github.sha }}
+      image-name: nemo_rl_container
+      dockerfile: docker/Dockerfile
+      image-label: nemo-rl
+      target: hermetic
+      build-args: |
+        MAX_JOBS=32
+        NEMO_RL_COMMIT=${{ github.sha }}
 
-  #tests:
-  #  name: Tests
-  #  needs: [build-container, pre-flight]
-  #  uses: ./.github/workflows/_run_test.yml
-  #  if: ${{ needs.pre-flight.outputs.test_level != 'none' }}
-  #  with:
-  #    RUNNER: self-hosted-azure
-  #    TIMEOUT: 180
-  #    UNIT_TEST_SCRIPT: |
-  #      cd /opt/nemo-rl
-  #      if [[ "${{ needs.pre-flight.outputs.test_level }}" =~ ^(L0|L1|L2)$ ]]; then
-  #        uv run --no-sync bash -x ./tests/run_unit.sh --cov=nemo_rl --cov-report=term-missing --cov-report=json -m \"not mcore\"
-  #        uv run --extra mcore bash -x ./tests/run_unit.sh --cov=nemo_rl --cov-report=term-missing --cov-report=json  -m mcore
-  #      else
-  #        echo Skipping unit tests for docs-only level
-  #      fi
-  #    DOC_TEST_SCRIPT: |
-  #      cd /opt/nemo-rl/docs
-  #      if [[ "${{ needs.pre-flight.outputs.test_level }}" =~ ^(docs|L0|L1|L2)$ ]]; then
-  #        uv run --no-sync sphinx-build -b doctest . _build/doctest
-  #      else
-  #        echo Skipping doc tests for level ${{ needs.pre-flight.outputs.test_level }}
-  #      fi
-  #    FUNCTIONAL_TEST_SCRIPT: |
-  #      cd /opt/nemo-rl
-  #      if [[ "${{ needs.pre-flight.outputs.test_level }}" =~ ^(L1|L2)$ ]]; then
-  #        time uv run --no-sync bash ./tests/functional/sft.sh
-  #        time uv run --no-sync bash ./tests/functional/grpo.sh
-  #        time uv run --no-sync bash ./tests/functional/grpo_megatron.sh
-  #        time uv run --no-sync bash ./tests/functional/grpo_multiturn.sh
-  #        time uv run --no-sync bash ./tests/functional/grpo_non_colocated.sh
-  #        time uv run --no-sync bash ./tests/functional/dpo.sh
-  #        time uv run --no-sync bash ./tests/functional/eval.sh
-  #        time uv run --no-sync bash ./tests/functional/eval_async.sh
-  #        time uv run --no-sync bash ./tests/functional/test_mcore_extra_installed_correctly.sh
-  #      else
-  #        echo Skipping functional tests for level ${{ needs.pre-flight.outputs.test_level }}
-  #      fi
-  #    # TODO: enable once we have convergence tests in CI
-  #    #CONVERGENCE_TEST_SCRIPT: |
-  #    #  cd /opt/nemo-rl
-  #    #  if [[ "${{ needs.pre-flight.outputs.test_level }}" =~ ^(L2)$  ]]; then
-  #    #    echo "Running convergence tests"
-  #    #    # Add your convergence test commands here
-  #    #    # uv run --no-sync bash ./tests/convergence/test.sh
-  #    #  else
-  #    #    echo "Skipping convergence tests for level ${{ needs.pre-flight.outputs.test_level }}"
-  #    #  fi
-  #    AFTER_SCRIPT: |
-  #      cd /opt/nemo-rl
-  #      cat <<EOF | tee -a $GITHUB_STEP_SUMMARY
-  #      # Test Summary for level: ${{ needs.pre-flight.outputs.test_level }}
+  tests:
+    name: Tests
+    needs: [build-container, pre-flight]
+    uses: ./.github/workflows/_run_test.yml
+    if: ${{ needs.pre-flight.outputs.test_level != 'none' }}
+    with:
+      RUNNER: self-hosted-azure
+      TIMEOUT: 180
+      UNIT_TEST_SCRIPT: |
+        cd /opt/nemo-rl
+        if [[ "${{ needs.pre-flight.outputs.test_level }}" =~ ^(L0|L1|L2)$ ]]; then
+          uv run --no-sync bash -x ./tests/run_unit.sh --cov=nemo_rl --cov-report=term-missing --cov-report=json -m \"not mcore\"
+          uv run --extra mcore bash -x ./tests/run_unit.sh --cov=nemo_rl --cov-report=term-missing --cov-report=json  -m mcore
+        else
+          echo Skipping unit tests for docs-only level
+        fi
+      DOC_TEST_SCRIPT: |
+        cd /opt/nemo-rl/docs
+        if [[ "${{ needs.pre-flight.outputs.test_level }}" =~ ^(docs|L0|L1|L2)$ ]]; then
+          uv run --no-sync sphinx-build -b doctest . _build/doctest
+        else
+          echo Skipping doc tests for level ${{ needs.pre-flight.outputs.test_level }}
+        fi
+      FUNCTIONAL_TEST_SCRIPT: |
+        cd /opt/nemo-rl
+        if [[ "${{ needs.pre-flight.outputs.test_level }}" =~ ^(L1|L2)$ ]]; then
+          time uv run --no-sync bash ./tests/functional/sft.sh
+          time uv run --no-sync bash ./tests/functional/grpo.sh
+          time uv run --no-sync bash ./tests/functional/grpo_megatron.sh
+          time uv run --no-sync bash ./tests/functional/grpo_multiturn.sh
+          time uv run --no-sync bash ./tests/functional/grpo_non_colocated.sh
+          time uv run --no-sync bash ./tests/functional/dpo.sh
+          time uv run --no-sync bash ./tests/functional/eval.sh
+          time uv run --no-sync bash ./tests/functional/eval_async.sh
+          time uv run --no-sync bash ./tests/functional/test_mcore_extra_installed_correctly.sh
+        else
+          echo Skipping functional tests for level ${{ needs.pre-flight.outputs.test_level }}
+        fi
+      # TODO: enable once we have convergence tests in CI
+      #CONVERGENCE_TEST_SCRIPT: |
+      #  cd /opt/nemo-rl
+      #  if [[ "${{ needs.pre-flight.outputs.test_level }}" =~ ^(L2)$  ]]; then
+      #    echo "Running convergence tests"
+      #    # Add your convergence test commands here
+      #    # uv run --no-sync bash ./tests/convergence/test.sh
+      #  else
+      #    echo "Skipping convergence tests for level ${{ needs.pre-flight.outputs.test_level }}"
+      #  fi
+      AFTER_SCRIPT: |
+        cd /opt/nemo-rl
+        cat <<EOF | tee -a $GITHUB_STEP_SUMMARY
+        # Test Summary for level: ${{ needs.pre-flight.outputs.test_level }}
 
-  #      ## Unit test results
-  #      \`\`\`json
-  #      $(if [[ "${{ needs.pre-flight.outputs.test_level }}" =~ ^(L0|L1|L2)$ ]]; then cat tests/unit/unit_results.json || echo "n/a"; else echo "Not run"; fi)
-  #      \`\`\`
+        ## Unit test results
+        \`\`\`json
+        $(if [[ "${{ needs.pre-flight.outputs.test_level }}" =~ ^(L0|L1|L2)$ ]]; then cat tests/unit/unit_results.json || echo "n/a"; else echo "Not run"; fi)
+        \`\`\`
 
-  #      ## Test Level: ${{ needs.pre-flight.outputs.test_level }}
-  #      EOF
-  #  secrets:
-  #    HF_TOKEN: ${{ secrets.HF_TOKEN }}
+        ## Test Level: ${{ needs.pre-flight.outputs.test_level }}
+        EOF
+    secrets:
+      HF_TOKEN: ${{ secrets.HF_TOKEN }}
 
-  #coverage:
-  #  name: Upload coverage to Codecov
-  #  needs: [tests]
-  #  if: ${{ contains('L0 L1 L2', needs.pre-flight.outputs.test_level) }}
-  #  runs-on: ubuntu-latest
-  #  steps:
-  #    - name: Checkout repository
-  #      uses: actions/checkout@v4
+  coverage:
+    name: Upload coverage to Codecov
+    needs: [tests]
+    if: ${{ contains('L0 L1 L2', needs.pre-flight.outputs.test_level) }}
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
 
-  #    - name: Download coverage artifact
-  #      uses: actions/download-artifact@v4
-  #      with:
-  #        name: unit-test-coverage-report
-  #        path: .
+      - name: Download coverage artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: unit-test-coverage-report
+          path: .
 
-  #    - name: Upload to Codecov
-  #      uses: codecov/codecov-action@v4
-  #      with:
-  #        token: ${{ secrets.CODECOV_TOKEN }}
-  #        file: ./coverage.json
-  #        flags: unit-tests
-  #        verbose: true
-  #        override_branch: ${{ github.event_name == 'merge_group' && 'main' || '' }}
+      - name: Upload to Codecov
+        uses: codecov/codecov-action@v4
+        with:
+          token: ${{ secrets.CODECOV_TOKEN }}
+          file: ./coverage.json
+          flags: unit-tests
+          verbose: true
+          override_branch: ${{ github.event_name == 'merge_group' && 'main' || '' }}
 
-  #CI_QA_Gate:
-  #  name: CI quality check
-  #  if: always()
-  #  runs-on: ubuntu-latest
-  #  needs:
-  #    - pre-flight
-  #    - lint-check
-  #    - sphinx-build
-  #    - tests
-  #  steps:
-  #    - name: main
-  #      env:
-  #        JOB_RESULTS: ${{ toJSON(needs) }}
-  #        # Job is considered successful if nothing was run, or if all jobs were successful (the tests run even if only docs were run b/c doctests are selected)
-  #        ALL_SUCCESS: >-
-  #          ${{
-  #            needs.lint-check.result == 'success' &&
-  #            (
-  #              needs.pre-flight.outputs.test_level == 'none' ||
-  #              (
-  #                needs.pre-flight.outputs.test_level != 'none' &&
-  #                needs.sphinx-build.result == 'success' &&
-  #                needs.tests.result == 'success' &&
-  #                (needs.mypy-check.result == 'success' || true)
-  #              )
-  #            )
-  #          }}
-  #        CI_SKIP: ${{ github.event.label.name == 'Skip CICD' }}
-  #        TEST_LEVEL: ${{ needs.pre-flight.outputs.test_level }}
-  #      run: |
-  #        SUMMARY=$(echo $JOB_RESULTS | jq 'to_entries[] | .key + ": " + .value.result' | tr -d '"')
-  #        echo '🤖: CICD Result for test level: ${{ needs.pre-flight.outputs.test_level }}' >> $GITHUB_STEP_SUMMARY
-  #        echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
+  CI_QA_Gate:
+    name: CI quality check
+    if: always()
+    runs-on: ubuntu-latest
+    needs:
+      - pre-flight
+      - lint-check
+      - sphinx-build
+      - tests
+    steps:
+      - name: main
+        env:
+          JOB_RESULTS: ${{ toJSON(needs) }}
+          # Job is considered successful if nothing was run, or if all jobs were successful (the tests run even if only docs were run b/c doctests are selected)
+          ALL_SUCCESS: >-
+            ${{
+              needs.lint-check.result == 'success' &&
+              (
+                needs.pre-flight.outputs.test_level == 'none' ||
+                (
+                  needs.pre-flight.outputs.test_level != 'none' &&
+                  needs.sphinx-build.result == 'success' &&
+                  needs.tests.result == 'success' &&
+                  (needs.mypy-check.result == 'success' || true)
+                )
+              )
+            }}
+          CI_SKIP: ${{ github.event.label.name == 'Skip CICD' }}
+          TEST_LEVEL: ${{ needs.pre-flight.outputs.test_level }}
+        run: |
+          SUMMARY=$(echo $JOB_RESULTS | jq 'to_entries[] | .key + ": " + .value.result' | tr -d '"')
+          echo '🤖: CICD Result for test level: ${{ needs.pre-flight.outputs.test_level }}' >> $GITHUB_STEP_SUMMARY
+          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
 
-  #        if [[ "$TEST_LEVEL" == "none" ]]; then
-  #          echo "No tests were run, passing gate" >> $GITHUB_STEP_SUMMARY
-  #          exit 0
-  #        fi
+          if [[ "$TEST_LEVEL" == "none" ]]; then
+            echo "No tests were run, passing gate" >> $GITHUB_STEP_SUMMARY
+            exit 0
+          fi
 
-  #        test "$ALL_SUCCESS" = "true" || test "$CI_SKIP" = "true"
+          test "$ALL_SUCCESS" = "true" || test "$CI_SKIP" = "true"
 
-  #DCO_merge_group:
-  #  name: DCO
-  #  if: github.event_name == 'merge_group'
-  #  runs-on: ubuntu-latest
-  #  steps:
-  #    - run: echo "The real DCO check happens on PRs only. This is a placeholder for the merge queue to keep the DCO check as a required status check."
+  DCO_merge_group:
+    name: DCO
+    if: github.event_name == 'merge_group'
+    runs-on: ubuntu-latest
+    steps:
+      - run: echo "The real DCO check happens on PRs only. This is a placeholder for the merge queue to keep the DCO check as a required status check."
